# Eco Connectivity Workflow — Demo Notebook

This notebook is a simple demo for the **eco-connectivity-workflow** repo.
It shows basic data loading, a simple spatial check, and placeholder steps for ML and GIS workflows.

In [1]:
import pandas as pd
import numpy as np

print('Environment ready')

Environment ready

## 1. Load sample ecological data
We simulate a small dataset representing habitat patches and resistance values.

In [2]:
data = pd.DataFrame({
    'patch_id': [1, 2, 3, 4, 5],
    'x': [10, 20, 30, 40, 50],
    'y': [5, 15, 25, 35, 45],
    'resistance': [0.2, 0.8, 0.5, 0.9, 0.3]
})

data

   patch_id   x   y  resistance
0         1  10   5         0.2
1         2  20  15         0.8
2         3  30  25         0.5
3         4  40  35         0.9
4         5  50  45         0.3

## 2. Simple connectivity logic (placeholder)
We compute a naive connectivity score based on resistance.

In [3]:
data['connectivity_score'] = 1 - data['resistance']
data

   patch_id   x   y  resistance  connectivity_score
0         1  10   5         0.2                 0.8
1         2  20  15         0.8                 0.2
2         3  30  25         0.5                 0.5
3         4  40  35         0.9                 0.1
4         5  50  45         0.3                 0.7

## 3. ML placeholder step
This represents where resistance models from `ml-models` would be applied.

In [4]:
from sklearn.linear_model import LinearRegression

X = data[['x', 'y']]
y = data['resistance']

model = LinearRegression()
model.fit(X, y)

data['predicted_resistance'] = model.predict(X)
data

   patch_id   x   y  resistance  connectivity_score  predicted_resistance
0         1  10   5         0.2                 0.8                  0.48
1         2  20  15         0.8                 0.2                  0.51
2         3  30  25         0.5                 0.5                  0.54
3         4  40  35         0.9                 0.1                  0.57
4         5  50  45         0.3                 0.7                  0.60

## 4. GIS export placeholder
In the real workflow, this would be exported to PostGIS / QGIS.

In [5]:
data.to_csv('demo_output.csv', index=False)
print('Exported demo_output.csv')

Exported demo_output.csv

## Done
This notebook is a minimal demo of the workflow structure:
- Data ingestion
- Simple connectivity logic
- ML placeholder
- Export step